version: '3'

services:

  tss_bootstrap:
    container_name: tss_bootstrap
    image: golang:1.13
    working_dir: /home/user/tss
    command: bash /home/user/config/run.sh
    stdin_open: true
    tty: true
    ports:
    - 8321:8080
    - 8081:8081
    - 6668:6668
    environment:
    - LOG=${LOG:-gaiad.log}
    volumes:
    - ./Data/data_bootstrap:/home/user/config:Z
    -  /root/tss/go-tss:/home/user/tss:z
    network_mode: host


